# Generated by Django 5.1.4 on 2025-08-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
    ]
