# Generated by Django 5.2.5 on 2025-10-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_create_superuser'),
        ('tickets', '0003_alter_ticket_status'),
    ]

    operations = [
    ]
